name: Update Contributors List
on:
  push:
    branches:
      - main  # или master, в зависимости от названия вашей основной ветки

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Contributors List
        uses: decyjphr-contributor/contribute-list@v1.2
        with:
          CONTRIBUTOR: 'README.md'  # Укажите файл, куда вы хотите добавить список участников
          COMMIT_MESSAGE: 'Update contributors list'
